---
  # Tasks: Install php composer on Ubuntu

  - name: "Install depencies"
    apt:
      name: "{{ item }}"
      update_cache: yes 
      state: present
    with_items:
      - curl
      - php-cli
      - php-mbstring
      - git
      - unzip

  - name: "Download composer"
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer
    
  - name: "Install composer"
    shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
    args:
      creates: /usr/local/bin/composer

  - name: rename composer.phar to composer
    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
    args:
      creates: /usr/local/bin/composer

  - name: make composer executable
    file: 
      path: /usr/local/bin/composer
      mode: a+x
      state: file
